### ISSUE TITLE
Don't check the API for non configured instances

### ISSUE THREAD

**Issue by RyanTheAllmighty** [nodecraft/ATLChecker#2]
I've been seeing alot of calls to "/v1/pack/Default" through the API and ask to see if you would be so kind as to not make an API call unless the user has set it up.

I'm not sure where users are getting non configured versions of the mods from, but a simple setting in the config for enabling the checker which is false by default or even having the pack name to check be blank by default and don't check for updates when it's a blank string.

This would be very much appreciated.

Thanks

**Comment by Orthus** [comment]
Patch has been created for this. Modpacks with the default config should no longer call the API.

**Comment by RyanTheAllmighty** [comment]
Cheers. Was just seeing invalid api calls every 3 seconds nearly from this
:/
